sonar.projectKey=kliarist_ccli
sonar.organization=kliarist
sonar.projectName=ccli
sonar.sources=src
sonar.exclusions=target/**
sonar.rust.lcov.reportPaths=lcov.info
sonar.scanner.skipJreProvisioning=true
